/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VoiceRecognizer;

import static VoiceRecognizer.Escucha.recognizer;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.speech.AudioException;
import javax.speech.Central;
import javax.speech.EngineModeDesc;
import javax.speech.EngineStateError;
import javax.speech.recognition.Recognizer;
import javax.speech.recognition.Result;
import javax.speech.recognition.ResultEvent;
import javax.speech.recognition.ResultToken;
import javax.speech.recognition.RuleGrammar;
import javax.swing.ImageIcon;

/**
 *
 * @author xyto_
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CreateAccount = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jt_FirstName_CreateAccount = new javax.swing.JTextField();
        jt_LastName_CreateAccount = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jt_Username_CreateAccount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jt_Day_CreateAccount = new javax.swing.JTextField();
        cb_Month_CreateAccount = new javax.swing.JComboBox<>();
        jt_Year_CreateAccount = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cb_Gender_CreateAccount = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cb_Location_CreateAccount = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jt_PhoneNumber_CreateAccount = new javax.swing.JTextField();
        jt_Password_CreateAccount = new javax.swing.JPasswordField();
        jt_ConfirmPassword_CreateAccount = new javax.swing.JPasswordField();
        jb_CreateAccount_CreateAccount = new javax.swing.JButton();
        jd_User = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jb_microphone_LogIn = new javax.swing.JButton();
        jt_Username_LogIn = new javax.swing.JTextField();
        jb_SignIn_LogIn = new javax.swing.JButton();
        jb_CreateAccount_LogIn = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        jd_CreateAccount.setTitle("CREATE YOUR ACCOUNT");
        jd_CreateAccount.setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Create your account");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        jt_FirstName_CreateAccount.setText("First");

        jt_LastName_CreateAccount.setText("Last");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Choose your username");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Create a password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Confirm your password");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Birthday");

        jt_Day_CreateAccount.setText("DAY");

        cb_Month_CreateAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jt_Year_CreateAccount.setText("YEAR");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Gender");

        cb_Gender_CreateAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Other", "Rather not say" }));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Location");

        cb_Location_CreateAccount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+1 –  Canada", "+1 –  United States", "+1 787 / 939 –  Puerto Rico", "+1 242 –  Bahamas", "+1 246 –  Barbados", "+1 264 –  Anguilla", "+1 268 –  Antigua and Barbuda", "+1 284 –  British Virgin Islands", "+1 345 –  Cayman Islands", "+1 441 –  Bermuda", "+1 473 –  Grenada", "+1 649 –  Turks and Caicos Islands", "+1 664 –  Montserrat", "+1 721 –  Sint Maarten", "+1 758 –  Saint Lucia", "+1 767 –  Dominica", "+1 784 –  Saint Vincent and the Grenadines", "+1 809 / 829 / 849 –  Dominican Republic", "+1 868 –  Trinidad and Tobago", "+1 869 –  Saint Kitts and Nevis", "+1 876 –  Jamaica", "+30 –  Greece", "+31 –  Netherlands", "+32 –  Belgium", "+33 –  France", "+34 –  Spain", "+350 –  Gibraltar", "+351 –  Portugal", "+352 –  Luxembourg", "+353 –  Ireland", "+354 –  Iceland", "+355 –  Albania", "+356 –  Malta", "+357 –  Cyprus", "+358 –  Finland", "+358 18 –  Åland Islands", "+359 –  Bulgaria", "+36 –  Hungary", "+500 –  Falkland Islands", "+500 x –  South Georgia and South Sandwich Islands", "+501 –  Belize", "+502 –  Guatemala", "+503 –  El Salvador", "+504 –  Honduras", "+505 –  Nicaragua", "+506 –  Costa Rica", "+507 –  Panama", "+508 –  Saint-Pierre and Miquelon", "+509 –  Haiti", "+51 –  Peru", "+52 –  Mexico", "+53 –  Cuba", "+54 –  Argentina", "+55 –  Brazil", "+56 –  Chile", "+57 –  Colombia", "+58 –  Venezuela", "+590 –  Guadeloupe", "+591 –  Bolivia", "+592 –  Guyana", "+593 –  Ecuador", "+595 –  Paraguay", "+596 –  Martinique", "+597 –  Suriname", "+598 –  Uruguay" }));
        cb_Location_CreateAccount.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_Location_CreateAccountItemStateChanged(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Phone number");

        jb_CreateAccount_CreateAccount.setText("CREATE ACCOUNT");

        javax.swing.GroupLayout jd_CreateAccountLayout = new javax.swing.GroupLayout(jd_CreateAccount.getContentPane());
        jd_CreateAccount.getContentPane().setLayout(jd_CreateAccountLayout);
        jd_CreateAccountLayout.setHorizontalGroup(
            jd_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreateAccountLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(jLabel1)
                .addContainerGap(315, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CreateAccountLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(cb_Gender_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jt_Username_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jt_ConfirmPassword_CreateAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                        .addComponent(jt_Password_CreateAccount, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jd_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_CreateAccountLayout.createSequentialGroup()
                            .addComponent(jt_Day_CreateAccount)
                            .addGap(18, 18, 18)
                            .addComponent(cb_Month_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jt_Year_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17))
                        .addGroup(jd_CreateAccountLayout.createSequentialGroup()
                            .addComponent(jt_FirstName_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jt_LastName_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jt_PhoneNumber_CreateAccount, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cb_Location_CreateAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_CreateAccountLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jb_CreateAccount_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(113, 113, 113))
        );

        jd_CreateAccountLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jt_FirstName_CreateAccount, jt_LastName_CreateAccount});

        jd_CreateAccountLayout.setVerticalGroup(
            jd_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreateAccountLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jd_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_FirstName_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_LastName_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jt_Username_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(jt_Password_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jt_ConfirmPassword_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jd_CreateAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jt_Day_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Month_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jt_Year_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_Gender_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(cb_Location_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jt_PhoneNumber_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jb_CreateAccount_CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jd_CreateAccountLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jt_FirstName_CreateAccount, jt_LastName_CreateAccount});

        javax.swing.GroupLayout jd_UserLayout = new javax.swing.GroupLayout(jd_User.getContentPane());
        jd_User.getContentPane().setLayout(jd_UserLayout);
        jd_UserLayout.setHorizontalGroup(
            jd_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );
        jd_UserLayout.setVerticalGroup(
            jd_UserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 521, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOG IN/SIGN IN");
        setResizable(false);

        jButton1.setText("Martha");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("imprimir Martha");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jb_microphone_LogIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Microphone.png"))); // NOI18N
        jb_microphone_LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_microphone_LogInMouseClicked(evt);
            }
        });

        jt_Username_LogIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jt_Username_LogIn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jt_Username_LogIn.setText("USERNAME");

        jb_SignIn_LogIn.setText("SIGN IN");
        jb_SignIn_LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_SignIn_LogInMouseClicked(evt);
            }
        });

        jb_CreateAccount_LogIn.setText("CREATE ACCOUNT");
        jb_CreateAccount_LogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_CreateAccount_LogInMouseClicked(evt);
            }
        });

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField1.setText("PASSWORD");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_microphone_LogIn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_CreateAccount_LogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPasswordField1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jb_SignIn_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jt_Username_LogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))))
                        .addGap(0, 224, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPasswordField1, jt_Username_LogIn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_microphone_LogIn)
                .addGap(68, 68, 68)
                .addComponent(jt_Username_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_SignIn_LogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jb_CreateAccount_LogIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPasswordField1, jt_Username_LogIn});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        System.out.println("John esta aqui: " + GPalabra.getGst());
    }//GEN-LAST:event_jButton2MouseClicked

    private void jb_CreateAccount_LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_CreateAccount_LogInMouseClicked
        // TODO add your handling code here:
        jd_CreateAccount.setModal(false);
        jd_CreateAccount.pack();
        jd_CreateAccount.setLocationRelativeTo(this);
        jd_CreateAccount.setVisible(true);
    }//GEN-LAST:event_jb_CreateAccount_LogInMouseClicked

    private void jb_microphone_LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_microphone_LogInMouseClicked
        // TODO add your handling code here:
        if (CambiarIconoMicrofono == 0) {
            jb_microphone_LogIn.setIcon(new ImageIcon(getClass().getResource("/Iconos/stopMicrophone.png")));
            CambiarIconoMicrofono++;
            Recognizer();
            System.out.println("Inicia");
        } else if (CambiarIconoMicrofono == 1) {
            jb_microphone_LogIn.setIcon(new ImageIcon(getClass().getResource("/Iconos/Microphone.png")));
            CambiarIconoMicrofono--;
            recognizer.suspend();
            System.out.println("Termine");
        }
    }//GEN-LAST:event_jb_microphone_LogInMouseClicked

    private void cb_Location_CreateAccountItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_Location_CreateAccountItemStateChanged
        // TODO add your handling code here:
        String CutPhoneCode = cb_Location_CreateAccount.getSelectedItem().toString();
        int BeginIndex = 0, EndIndex = CutPhoneCode.length();

        for (int i = 0; i < CutPhoneCode.length(); i++) {
            char Revisar = CutPhoneCode.charAt(i);
            if (Revisar == '+') {
                BeginIndex = i;
            }
            if (Revisar == '/' || Revisar == '–') {
                EndIndex = i;
            }
        }

        String PhoneCode = CutPhoneCode.substring(BeginIndex, EndIndex);
        jt_PhoneNumber_CreateAccount.setText(PhoneCode);
    }//GEN-LAST:event_cb_Location_CreateAccountItemStateChanged

    private void jb_SignIn_LogInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_SignIn_LogInMouseClicked
        // TODO add your handling code here:
        jd_User.setModal(false);
        jd_User.pack();
        jd_User.setLocationRelativeTo(this);
        jd_User.setVisible(true);
    }//GEN-LAST:event_jb_SignIn_LogInMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_Gender_CreateAccount;
    private javax.swing.JComboBox<String> cb_Location_CreateAccount;
    private javax.swing.JComboBox<String> cb_Month_CreateAccount;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton jb_CreateAccount_CreateAccount;
    private javax.swing.JButton jb_CreateAccount_LogIn;
    private javax.swing.JButton jb_SignIn_LogIn;
    private javax.swing.JButton jb_microphone_LogIn;
    private javax.swing.JDialog jd_CreateAccount;
    private javax.swing.JDialog jd_User;
    private javax.swing.JPasswordField jt_ConfirmPassword_CreateAccount;
    private javax.swing.JTextField jt_Day_CreateAccount;
    private javax.swing.JTextField jt_FirstName_CreateAccount;
    private javax.swing.JTextField jt_LastName_CreateAccount;
    private javax.swing.JPasswordField jt_Password_CreateAccount;
    private javax.swing.JTextField jt_PhoneNumber_CreateAccount;
    private javax.swing.JTextField jt_Username_CreateAccount;
    private javax.swing.JTextField jt_Username_LogIn;
    private javax.swing.JTextField jt_Year_CreateAccount;
    // End of variables declaration//GEN-END:variables
    Recognizer recognizer;
    String gst = "";
    String Palabra = "";
    Escucha GPalabra = new Escucha(Palabra);
    int CambiarIconoMicrofono = 0;
    Connection Conect = null;

    public void Recognizer() {
        try {
            recognizer = Central.createRecognizer(new EngineModeDesc(Locale.ROOT));
            recognizer.allocate();

            FileReader grammar1 = new FileReader("c:/SimpleGrammarES2.txt");

            RuleGrammar rg = recognizer.loadJSGF(grammar1);
            rg.setEnabled(true);

            System.out.println(GPalabra.getGst());
            recognizer.addResultListener(new Escucha(GPalabra));

            System.out.println("Empieze Dictado");
            recognizer.commitChanges();

            recognizer.requestFocus();
            recognizer.resume();
        } catch (Exception e) {
            System.out.println("Exception en " + e.toString());
            e.printStackTrace();
            System.exit(0);
        }
    }

    public void ConectarDB() {
        try {
            String connectionUrl = "jdbc:sqlserver://;database=Northwind;integratedSecurity=true;";
            Conect = DriverManager.getConnection(connectionUrl);
            System.out.println("Conectado.");
        } catch (SQLException ex) {
            System.out.println("Error.");
        }
    }
}
